sudo: required
language: python
python:
  - "3.5"

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker build -t router .
  - docker pull redis:3
  - mkdir -p redis-vol
  - docker swarm init --advertise-addr 127.0.0.1

script:
  - docker stack deploy -c docker-compose.yml dynx
  - sleep 30
  - python test/test_integration.py
  - docker service logs dynx_openresty-dyn
